// Runs the 17 Sprint 1 API scenarios against the real app and writes API_TESTING.md
// with the ACTUAL request / status / response of each call.
// Usage (from backend/):  node ../tests/api/generate-report.js
const fs = require('fs');
const path = require('path');
const { createApp } = require('../../backend/app');
const { createService } = require('../../backend/service');

const valid = { name: 'Ravi Kumar', mobile: '9876543210', email: 'ravi@example.com', password: 'secret1', confirmPassword: 'secret1' };
let id;

const cases = [
  ['Successful farmer registration', 'POST', '/api/register', () => valid, 201],
  ['Registration with empty name', 'POST', '/api/register', () => ({ ...valid, mobile: '9000000001', name: '' }), 400],
  ['Registration with invalid phone', 'POST', '/api/register', () => ({ ...valid, mobile: '12345' }), 400],
  ['Registration with password shorter than 6 characters', 'POST', '/api/register', () => ({ ...valid, mobile: '9000000002', password: '123', confirmPassword: '123' }), 400],
  ['Registration with mismatched password', 'POST', '/api/register', () => ({ ...valid, mobile: '9000000003', confirmPassword: 'other' }), 400],
  ['Registration with invalid email', 'POST', '/api/register', () => ({ ...valid, mobile: '9000000004', email: 'bad-email' }), 400],
  ['Duplicate phone number', 'POST', '/api/register', () => valid, 409],
  ['Successful farmer login', 'POST', '/api/login', () => ({ mobile: valid.mobile, password: valid.password }), 200],
  ['Login with wrong password', 'POST', '/api/login', () => ({ mobile: valid.mobile, password: 'wrong' }), 401],
  ['Login with unknown phone number', 'POST', '/api/login', () => ({ mobile: '9111111111', password: 'secret1' }), 401],
  ['Get existing farmer profile', 'GET', () => '/api/farmers/' + id, () => undefined, 200],
  ['Get non-existing farmer profile', 'GET', '/api/farmers/9999', () => undefined, 404],
  ['Successful profile update', 'PUT', () => '/api/farmers/' + id, () => ({ name: 'Ravi K', email: 'ravik@example.com', location: 'Coimbatore', farmSize: '4', mainCrop: 'Rice' }), 200],
  ['Profile update with invalid email', 'PUT', () => '/api/farmers/' + id, () => ({ name: 'Ravi K', email: 'bad' }), 400],
  ['Successful admin login', 'POST', '/api/admin/login', () => ({ username: 'admin', password: 'admin123' }), 200],
  ['Admin login with wrong password', 'POST', '/api/admin/login', () => ({ username: 'admin', password: 'wrong' }), 401],
  ['Admin login with missing username/password', 'POST', '/api/admin/login', () => ({}), 400]
];

(async () => {
  const server = createApp(createService()).listen(0);
  await new Promise((r) => server.once('listening', r));
  const base = 'http://127.0.0.1:' + server.address().port;
  let out = '# API Testing - Sprint 1\n\n';
  out += 'Generated by `tests/api/generate-report.js` on ' + new Date().toISOString() + '.\n';
  out += 'Every request below was actually sent to the running Express app and the response recorded.\n\n';
  let pass = 0;
  for (let i = 0; i < cases.length; i++) {
    const [title, method, p, bodyFn, expected] = cases[i];
    const url = typeof p === 'function' ? p() : p;
    const body = bodyFn();
    const res = await fetch(base + url, {
      method, headers: { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body)
    });
    const data = await res.json();
    if (i === 0) id = data.farmer.id;
    const ok = res.status === expected;
    if (ok) pass++;
    out += `## A${i + 1}. ${title}\n\n`;
    out += `- **Request:** \`${method} ${url}\`\n`;
    if (body !== undefined) out += '- **Body:**\n\n```json\n' + JSON.stringify(body, null, 2) + '\n```\n\n';
    out += `- **Expected status:** ${expected}\n- **Actual status:** ${res.status}\n`;
    out += `- **Message:** ${data.message || '(none)'}\n- **Result:** ${ok ? 'PASS' : 'FAIL'}\n\n`;
    out += '```json\n' + JSON.stringify(data, null, 2) + '\n```\n\n';
  }
  out += `## Summary\n\nTotal: ${cases.length}  |  Passed: ${pass}  |  Failed: ${cases.length - pass}\n`;
  fs.writeFileSync(path.join(__dirname, '..', '..', 'API_TESTING.md'), out);
  console.log(`API report written. Total ${cases.length}, passed ${pass}, failed ${cases.length - pass}`);
  server.close();
})();
